language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libudev-dev
      - libusb-1.0-0-dev
      - libffi-dev
      - libssl-dev
      - swig

install:
  - pip install "pip>=7.0.2" wheel
  - $TRAVIS_BUILD_DIR/dev-requirements.py
  - pip install -e .

script:
  - coverage run setup.py test

after_success:
  - coveralls
